### PR TITLE
add twig extensions before disabling plugin

### PR DESCRIPTION
**Pull request by clarknelson**
this will prevent twig errors after disabling the plugin in the settings

### CODE REVIEW

**Comment by roelvanhintum** [comment]
@clarknelson is disabling the plugin causing errors? Or the frontend after disabling? If it is the latter, i don't think it's good practice to load extensions when the plugin is disabled.

**Comment by clarknelson** [comment]
well when I disable the plugin in the settings, I get a twig error for every 'nonce()' on my page. It would be nice if we could enable / disable in one place. otherwise I would have to remove all the nonce tags after disabling, and then add them all back after enabling. I wonder how other plugins handle this.

**Comment by roelvanhintum** [comment]
@clarknelson i see what you mean: Load them for `!$settings->enabled`. I mixed it up with actually disabling the plugin from the craft settings page.

**Comment by roelvanhintum** [comment]
Sorry for the delay. Just released in 1.3.1

**Pull request merged**
